---
- name: My webserver playbook
  hosts: ansibleclient

  tasks:
    - name: Package Installation
      package: name=httpd state=present

    - name: File config
      copy: dest="/var/www/html/index.html" content="<h1>This server has installed using Jenkins and Ansible using Poll SCM feature</h1>" 

    - name: Starting web services
      service: name=httpd state=started

    - name: Creating a new user
      user: name=nitest state=present
